### ISSUE TITLE
Cannot build the elm client

### ISSUE THREAD

**Issue by mcesaro** [kongo2002/statser#18]
Hi, I made statser work with [beam_stats](<https://github.com/xandkar/beam_stats>) under OTP 24.
Although the server seems to work pretty well, I'm not able to build the `elm` client using the provided makefile.
This is what I get:
```sh
max@max:~/work/uatu/statser$ make client
make -C elm-client
make[1]: Entering directory '/home/max/work/uatu/statser/elm-client'
yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
make[1]: *** [Makefile:16: dist/app.js] Error 1
make[1]: Leaving directory '/home/max/work/uatu/statser/elm-client'
make: *** [Makefile:9: client] Error 2
```
I'm using elm 0.19.1 but I can't tell if this might be a problem.
Note: I'm also using `node.js`  v13.9.0.

**Comment by mcesaro** [comment]
I found the culprit. It seems that with recent Ubuntu distributions you need to remove the `yarn` package provided by Canonical and then install the version from the official website. I found also a reference in [StackOverflow](<https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one>) to the same problem.

**Comment by kongo2002** [comment]
Hi @mcesaro 

sorry for responding so delayed. Glad you fixed the issue yourself and thank you for reporting the fix for future reference :+1: 

Cheers,
Gregor
